[project]
name = "booknlp"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "en-core-web-sm",
    "onnxruntime>=1.23.2",
    "onnxscript>=0.6.0",
    "optimum-onnx[onnxruntime]>=0.1.0",
    "optimum[onnxruntime]>=1.17.1",
    "spacy>=3.8.11",
    "torch==2.9.1+cpu",
    "torchvision==0.24.1+cpu",
    "transformers>=4.41.0,<5.0.0",
]


[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
torch = [
    { index = "torch-all" },
]
torchvision = [
    { index = "torch-all" },
]

[[tool.uv.index]]
name = "torch-all"
url = "https://download.pytorch.org/whl/"
explicit = true
